1. Overfitting - training data overfiti, so did not learn pattern (good in training and sucks in testing)
2. Underfitting - underfitting did not learn anything, also did not learn durung training
3. Real world analogy
4. Random forest
5. RF solves overfiitng and underfitting

Overfitting on Decision Tree

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,precision_score,recall_score 

from sklearn.model_selection import GridSearchCV

In [2]:
df = load_iris(as_frame=True).frame
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [3]:
X = df.drop(['target'], axis=1)
y = df['target'] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42, stratify=y)

In [5]:
model = DecisionTreeClassifier() 

model.fit(X_train,y_train) 
y_pred = model.predict(X_test) 

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [7]:
grid = {
    "criterion" : ['gini','entropy'],
    "max_depth" : [1,2,3,4,5,6,7,8,None]
}

grid_search = GridSearchCV(
    estimator = model,
    param_grid= grid,
    cv =5
) 

grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, None]})

# Training on different depths

In [12]:
model1 = DecisionTreeClassifier(max_depth=2) 

model1.fit(X_train,y_train) 

## Training data accuracy 
y_pred_train = model1.predict(X_train)
print(f"Training accuray: {accuracy_score(y_train,y_pred_train)}") 

## Testing accuracy
y_pred = model1.predict(X_test) 

print(f"Testing accuray: {accuracy_score(y_test,y_pred)}")

Training accuray: 0.9666666666666667
Testing accuray: 0.9333333333333333

In [15]:
model_2 = DecisionTreeClassifier(max_depth=3) 

model_2.fit(X_train,y_train) 

## Training data accuracy 
y_pred_train = model_2.predict(X_train)
print(f"Training accuray: {accuracy_score(y_train,y_pred_train)}") 

## Testing accuracy
y_pred = model_2.predict(X_test) 

print(f"Testing accuray: {accuracy_score(y_test,y_pred)}")

Training accuray: 0.9833333333333333
Testing accuray: 0.9666666666666667

In [16]:
model_3 = DecisionTreeClassifier(max_depth=4) 

model_3.fit(X_train,y_train) 

## Training data accuracy 
y_pred_train = model_3.predict(X_train)
print(f"Training accuray: {accuracy_score(y_train,y_pred_train)}") 

## Testing accuracy
y_pred = model_3.predict(X_test) 

print(f"Testing accuray: {accuracy_score(y_test,y_pred)}")

Training accuray: 0.9916666666666667
Testing accuray: 0.9666666666666667

In [17]:
model_4 = DecisionTreeClassifier(max_depth=5) 

model_4.fit(X_train,y_train) 

## Training data accuracy 
y_pred_train = model_4.predict(X_train)
print(f"Training accuray: {accuracy_score(y_train,y_pred_train)}") 

## Testing accuracy
y_pred = model_4.predict(X_test) 

print(f"Testing accuray: {accuracy_score(y_test,y_pred)}")

Training accuray: 1.0
Testing accuray: 0.9666666666666667

In [19]:

## Training accuracy with grid search

## Training data accuracy 
y_pred_train = grid_search.predict(X_train)
print(f"Training accuray: {accuracy_score(y_train,y_pred_train)}") 

## Testing accuracy
y_pred = grid_search.predict(X_test) 

print(f"Testing accuray: {accuracy_score(y_test,y_pred)}")

Training accuray: 1.0
Testing accuray: 0.9666666666666667

# Ensamble learning - (making different models and training with different datasets and finidng the true truth)

# For random Forest - 
1. Random Sampling 
2. Random Feature Sampling 
3. Or do both
4. Bagging means -Bootstraping (dviving a dataset), aggregations (adding all answers of models)

# Why random forest is better 
1. Bias - Complexity of the model
2. Variance - Adaptability with training data 
so we need to balance it because they have inverse relationship,  so we need optimum values for both

By default decision tree is low bias and high variance

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,precision_score,recall_score 

from sklearn.model_selection import GridSearchCV

In [21]:
df = load_breast_cancer(as_frame=True).frame 
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [22]:
df.shape

(569, 31)

In [23]:
X= df.drop(['target'],axis=1)
y = df['target'] 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [24]:
model = DecisionTreeClassifier()
model.fit(X_train,y_train) 

y_pred = model.predict(X_test) 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89        42
           1       0.96      0.90      0.93        72

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114

In [25]:
grid = {
    "criterion" : ['gini','entropy'],
    "max_depth" : [1,2,3,4,5,6,7,8,None]
}

grid_search = GridSearchCV(
    estimator = model,
    param_grid= grid,
    cv =5
) 

grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, None]})

In [26]:
y_pred = grid_search.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90        42
           1       0.94      0.94      0.94        72

    accuracy                           0.93       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114

In [27]:
model_1 = DecisionTreeClassifier(max_depth=2)

model_1.fit(X_train,y_train)

# training data accuracy
y_pred_train = model_1.predict(X_train)
print(f"Training Accuracy: {accuracy_score(y_train,y_pred_train)}")


# testing accuracy
y_pred = model_1.predict(X_test)

print(f"Testing Accuracy: {accuracy_score(y_test,y_pred)}")

Training Accuracy: 0.9582417582417583
Testing Accuracy: 0.8947368421052632

In [28]:
model_2 = DecisionTreeClassifier(max_depth=3)

model_2.fit(X_train,y_train)

# training data accuracy
y_pred_train = model_2.predict(X_train)
print(f"Training Accuracy: {accuracy_score(y_train,y_pred_train)}")


# testing accuracy
y_pred = model_2.predict(X_test)

print(f"Testing Accuracy: {accuracy_score(y_test,y_pred)}")

Training Accuracy: 0.9758241758241758
Testing Accuracy: 0.9385964912280702

In [ ]:
model_3 = DecisionTreeClassifier(max_depth=4)

model_3.fit(X_train,y_train)

# training data accuracy
y_pred_train = model_3.predict(X_train)
print(f"Training Accuracy: {accuracy_score(y_train,y_pred_train)}")


# testing accuracy
y_pred = model_3.predict(X_test)

print(f"Testing Accuracy: {accuracy_score(y_test,y_pred)}")